name: Test Environment Setup

on:
  # 이 GitHub Actions 워크플로우는 월요일부터 금요일까지 매일 UTC 기준 오전 3시에 실행되도록 예약되어 있습니다.
  # 또한 "workflow_dispatch" 이벤트를 사용하여 수동으로 트리거할 수도 있습니다.
  # schedule:
  #   - cron: '0 21 * * 1-5'
  # workflow_dispatch:

    push:
      branches:
        - main

jobs:
  setup-test-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install
        npm install axios
        npm install --save-dev @types/node

    - name: Run TypeScript tests
      run: |
       echo "Start testing"
       npx jest --config jest.config.js
